Added logs, Allure reporting and CircleCi
Alisa1106/Automationpractice pull request #5
Opened 2021-07-18 18:10 UTC by Alisa1106

2021-07-19 20:23 UTC, vchesnakoutest requested changes
please make fixes

2021-07-19 20:23 UTC, vchesnakoutest commented on src/main/java/pages/AuthenticationPage.java
>          return new CreateAccountPage(driver);
посмотрел сейчас этот метод и все-таки предложил бы его разбить на 2 мелких. 1 на заполнение email, второй на  нажатие кнопки Create. Пототому что в теории могут быть сценарии когда нам надо будет ничего не ввести и нажать кнопку Create и тд. Лучше такие соединения делать в степах все-таки.

2021-07-19 20:23 UTC, vchesnakoutest commented on src/main/java/pages/AuthenticationPage.java
> +        log.info("Open authentication page URL " + AUTOMATIONPRACTICE_AUTHENTICATION_PAGE_URL);
как вариант, лог можно сделать только в базовом методе super.openPage и просто выводить урл который мы ему передаем, этого как правило достаточно. Т.е. "Open URL: https://......"

2021-07-19 20:23 UTC, vchesnakoutest commented on src/main/java/pages/CreateAccountPage.java
> +        log.info("Click button 'Register'.");
почему бы в самих методах writeText и select не сделать логирование, чтобы не приходилось сюда вставлять логи под каждое действие ?

2021-07-19 20:23 UTC, vchesnakoutest commented on src/main/java/pages/HeaderPage.java
> +        log.info("Move to cart dropdown");
то же самое, лучше сделать одно общее логирование в методе WebDriverUtils.moveToElement

2021-07-19 20:23 UTC, vchesnakoutest commented on src/main/java/pages/YourAddressesPage.java
>          new Input(driver, "for future reference.").writeText(address.getAddressAlias());
то же самое, лучше сделать логирование внутри методов

2021-07-19 20:23 UTC, vchesnakoutest commented on src/test/resources/allure.properties
> +allure.link.tms.pattern=https://github.com/{}
можно эти удалить в принципе

2021-07-19 21:01 UTC, Alisa1106 commented on src/main/java/pages/AuthenticationPage.java
>          return new CreateAccountPage(driver);
+

2021-07-20 17:22 UTC, vchesnakoutest approved these changes

2021-07-20 17:55 UTC, merged